name: Fetch Posts

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一零点执行
  workflow_dispatch:      # 允许手动触发

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    
    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
        
      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      # 安装项目依赖（包括从 package.json 中安装的所有依赖）
      - name: Install dependencies
        run: npm install
          
      # 执行脚本以获取文章数据
      - name: Run fetch script
        run: node src/data/getPost.js
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          MAX_ARTICLES_PER_CATEGORY: ${{ secrets.MAX_ARTICLES_PER_CATEGORY }}
          
      # 检查是否有变更，并在有变更时提交
      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/data/articles_list.ts
          git diff --quiet && git diff --staged --quiet || (git commit -m "自动更新文章列表" && git push)
